name: android_alarm_manager_example
description: Demonstrates how to use the android_alarm_manager plugin.

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager:
    path: ../
  e2e: ^0.2.1
  path_provider: ^1.3.1
  flutter_ringtone_player: ^2.0.0
  audioplayer: ^0.5.2
  nova_alarm_plugin: ^0.1.0


dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
